tst

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -28,7 +28,27 @@ steps:
   
   
 
-  #
+  # ---------------------------------------------------------
+  # 1.1) Initialize Database (create table)
+  # ---------------------------------------------------------
+  - name: python:3.11
+    id: "Init Database"
+    entrypoint: bash
+    args:
+      - "-c"
+      - |
+        echo "🔧 Loading environment variables from .env..."
+        if [ -f .env ]; then
+            set -o allexport
+            source .env
+            set +o allexport
+        else
+          echo "⚠ .env file not found!"
+          exit 1
+        fi
+        cd app
+        pip install -r requirements.txt
+        INIT_DB_ONLY=true python app.py
   # ----------------------------------------------------------
   # 2) Build Docker Image with UNIQUE TAG
   # ----------------------------------------------------------
@@ -39,6 +59,8 @@ steps:
         "build",
         "-t",
         "${_IMAGE}:${_TAG}",
+        "-f",
+        "app/Dockerfile",
         "."
       ]
 
@@ -66,7 +88,7 @@ steps:
       - |
         echo "🚀 Starting deployment to GKE..."
 
-        gcloud container clusters get-credentials product-gke-cluster \
+        gcloud container clusters get-credentials products-gke-cluster1 \
           --zone=us-central1-a \
           --project=my-project-app-477009
         echo "📦 Applying Kubernetes manifests..."
